name: znet artifact

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version: ['1.17']
        platform: [linux, linux-arm64, windows, darwin]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - name: Build
      run: GOOS=$PLATFORM GOARCH=amd64 go build -o myapp-${{ matrix.platform }} ./cmd/myapp
      env:
        PLATFORM: ${{ matrix.platform }}

    - name: Archive artifact
      uses: actions/upload-artifact@v2
      with:
        name: myapp-${{ matrix.platform }}-artifact
        path: ./myapp-${{ matrix.platform }}
